run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly

output:
  formats: colored-text-line
  print-issued-lines: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - goimports
    - bodyclose
  disable:
    - gocyclo
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "Error return value of .* is not checked"
      linters:
        - errcheck
      source: ".*_test.go"

  exclude-use-default: false

  max-issues-per-linter: 0
  max-same-issues: 0